### ISSUE TITLE
Unable to set a background color for a detail row in the Statistics module

### ISSUE THREAD

**Issue by Mathire** [HafisCZ/sf-tools#27]
Code used for the detail row:
```
# Detail row
show Gilda as Guild
background @blue
width @max
```
As can be seen in the screenshot, `width @max` does work (guild name is in the middle of a max row), whilst `background @blue` doesn't apply. 

Tried on all the three tabs (players, guild and browse) and results are the same.

![Detail row background issue](https://user-images.githubusercontent.com/112318175/188208562-c545f4c5-71a8-4be7-9e9d-2d73e49649b5.jpeg)

**Comment by HafisCZ** [comment]
Fixed by 38733730c57f3a73091e247672a3ea595326fb30
