### ISSUE TITLE
Is there any way that I can export a table with CSV format?

### ISSUE THREAD

**Issue by xavi-ortega** [HafisCZ/sf-tools#58]
I was thinking of creating a chart to visualize my progress over the months and I saw that I can copy the table, but I would like to export the data in CSV format, or have a way of visualizing the data in a line chart for example.

I suppose that the data visualization inside SFTools is too much effort for the use case that it represents, but exporting to CSV shouldn't be a big deal

**_Example_**
Let's say I've got this table
![image](https://user-images.githubusercontent.com/14571996/233623975-2acf1994-c8a3-41d2-8386-eadd623719a8.png)

I would expect an output like this (the date in ascending order):
```csv
Date,Level,Album,Awards,Ratio,Intelligence,60/40,55/45,Resistance,60/40,55/45
19.03.2023 21:12,610,100.00%,100 H,56/44,263601,303221,247069,202147,175734,215674
31.03.2023 00:06,612,100.00%,100 H,56/44,265602,306152,249457,204101,177068,217311
21.04.2023 13:04,613,100.00%,100 H,56/44,270085,311982,254208,207988,180057,220979
```

And then I can use a plotting tool like [CSV Plot](https://www.csvplot.com/) to play around with the stats (obviously with more data it'd be cooler):
![image](https://user-images.githubusercontent.com/14571996/233625776-29a0df84-5074-481a-be5a-ff46edff5eed.png)
![image](https://user-images.githubusercontent.com/14571996/233625949-dc778743-94d5-4006-8f6c-163901c3ddb0.png)
![image](https://user-images.githubusercontent.com/14571996/233626039-cccfa328-4ba5-47a3-8121-36cc50f94a59.png)

**Comment by HafisCZ** [comment]
Hi, at this moment it's not possible. I will try to add it in tho, seems like somewhat useful feature since you can work with CSVs in excel as well.

**Comment by xavi-ortega** [comment]
Sounds good! I'll try then to save data more frequently, so the chart will look cooler 😄

**Comment by HafisCZ** [comment]
Hi, I have added the option to export table to CSV to https://beta.sftools.mar21.eu/ 🙂 if there are any issues let me know

**Comment by xavi-ortega** [comment]
Seems to be working fine. Can't wait to have it in the release version, so I can test it with all my data!
