### ISSUE TITLE
New steam log-in option

### ISSUE THREAD

**Issue by sinkolon** [HafisCZ/sf-tools#62]
I just connected my accounts to steam with the new option. Now when i try to use my account on sftools it says:

"You need to login with your account in order to access this character" 

I do not quite understand that actually. What i have to do?

**Comment by HafisCZ** [comment]
You just need to use your S&F Account name + password and it should work as before

**Comment by sinkolon** [comment]
I am using same name and password actually.
![1](https://github.com/HafisCZ/sf-tools/assets/133272621/885b441a-a99e-454f-aeec-1a6e2880ac55)
![2](https://github.com/HafisCZ/sf-tools/assets/133272621/903e6673-76d4-46ae-8413-021c4b270e52)

**Comment by HafisCZ** [comment]
You have to use just the name without the @ at the end. So instead of `name@server` you use only `name`.

**Comment by sinkolon** [comment]
Okay i solved now. Since i connected my accounts with steam, my e-mail addresses reseted. I just re-connected my accounts to my former mail address.
